[profile.default]

# Paths
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"]

# Metadata
metadata = true
metadata_hash = "none"          # Disable IPFS
use_literal_content = true      # Embed literal source code

# Optimizer Settings
via_ir = true
optimizer = true
optimizer_runs = 200

# Monad Network Configuration
eth-rpc-url = "https://testnet-rpc.monad.xyz"
chain_id = 10143